repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
    - id: name-tests-test
      args: ['--django']
    - id: debug-statements
    - id: end-of-file-fixer
      types: [python]
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: requirements-txt-fixer
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: ["--ignore", "E501,E203,W503"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
    - id: mypy
- repo: local
  hooks:
    - id: unittest
      name: unittest
      entry: venv/bin/python -m unittest discover
      language: python
      always_run: true
      pass_filenames: false
